"use client";

import React, { useMemo, useState } from "react";
import { ClaimDecision } from "@/hooks/useStellarWallet";
import { applyDemoAction, bootstrapIssuedDemo, emptyDemoState } from "./aidDemoState";
import type { DemoState, DemoStatus } from "./aidDemoState";

export type AidMode = "demo" | "live";
export type VoucherCategory = "Food" | "Medicine" | "Shelter" | "Other";

interface AidTabProps {
  isConnected: boolean;
  address: string | null;
  isLoading: boolean;
  createCampaign: (input: { campaignId: string; token: string }) => Promise<any>;
  fundCampaign: (input: { campaignId: string; amount: string }) => Promise<any>;
  approveMerchant: (input: { merchant: string; profileHash: string }) => Promise<any>;
  createCase: (input: { campaignId: string; caseId: string; caseRecordHash: string }) => Promise<any>;
  issueVoucher: (input: { voucherId: string; campaignId: string; caseId: string; merchant: string; amount: string; category: VoucherCategory; purposeHash: string; expiresAt: number }) => Promise<any>;
  redeemVoucher: (input: { voucherId: string; contentDigest: string; evidenceRecordId: string }) => Promise<any>;
  appendEvidenceRevision: (input: { voucherId: string; contentDigest: string; evidenceRecordId: string }) => Promise<any>;
  freezeClaim: (input: { voucherId: string; reasonHash: string }) => Promise<any>;
  decideClaim: (input: { voucherId: string; decision: ClaimDecision; reasonHash: string }) => Promise<any>;
}

const DEMO_CAMPAIGN_ID = "a".repeat(64);
const DEMO_CASE_ID = "b".repeat(64);
const DEMO_VOUCHER_ID = "c".repeat(64);
const DEMO_MERCHANT = "GDEMOAIDMERCHANT000000000000000000000000000000000000000000";

export default function AidTab(props: AidTabProps) {
  const { isConnected, address, isLoading, createCampaign, fundCampaign, approveMerchant, createCase, issueVoucher, redeemVoucher, appendEvidenceRevision, freezeClaim, decideClaim } = props;
  const [mode, setMode] = useState<AidMode>("demo");
  const [available, setAvailable] = useState(0);
  const [reserved, setReserved] = useState(0);
  const [paid, setPaid] = useState(0);
  const [status, setStatus] = useState<DemoStatus>("empty");
  const [history, setHistory] = useState<string[]>([]);
  const [message, setMessage] = useState("Demo starts empty: fund/issue, redeem evidence[0], then approve or dispute.");
  const [error, setError] = useState("");
  const [pending, setPending] = useState("");
  const [fundAmount, setFundAmount] = useState("100");
  const [campaignId, setCampaignId] = useState("");
  const [token, setToken] = useState("");
  const [merchant, setMerchant] = useState("");
  const [merchantProfileHash, setMerchantProfileHash] = useState("");
  const [caseId, setCaseId] = useState("");
  const [caseRecordHash, setCaseRecordHash] = useState("");
  const [voucherId, setVoucherId] = useState("");
  const [purposeHash, setPurposeHash] = useState("");
  const [voucherAmount, setVoucherAmount] = useState("25");
  const [category, setCategory] = useState<VoucherCategory>("Food");
  const [contentDigest, setContentDigest] = useState("");
  const [evidenceRecordId, setEvidenceRecordId] = useState("");
  const [revisionDigest, setRevisionDigest] = useState("");
  const [revisionRecordId, setRevisionRecordId] = useState("");
  const [reasonHash, setReasonHash] = useState("");
  const [decisionReasonHash, setDecisionReasonHash] = useState("");
  const [hasRevision, setHasRevision] = useState(false);
  const [walkthrough, setWalkthrough] = useState<{ name: "clean" | "disputed"; step: number } | null>(null);
  const total = useMemo(() => available + reserved + paid, [available, reserved, paid]);
  const liveDisabled = mode === "live" && (!isConnected || isLoading);
  const demoState = (): DemoState => ({ available, reserved, paid, status, hasRevision, history });
  const setDemoState = (state: DemoState) => { setAvailable(state.available); setReserved(state.reserved); setPaid(state.paid); setStatus(state.status); setHasRevision(state.hasRevision); setHistory(state.history); };
  const applyLocalDemoAction = (action: Parameters<typeof applyDemoAction>[1]) => setDemoState(applyDemoAction(demoState(), action));
  const run = async (label: string, fn: () => Promise<void>) => { setError(""); setPending(label); try { await fn(); } catch (e: any) { setError(e.message || String(e)); } finally { setPending(""); } };
  const resetDemo = () => { setDemoState(emptyDemoState()); setWalkthrough(null); setMessage("Local demo reset. No on-chain transaction was sent."); };
  const fund = () => run("Funding campaign", async () => { const amount = Number(fundAmount); if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "fund", amount }); setMessage(`Local demo funded ${amount.toFixed(2)} units. Never on-chain.`); return; } if (!Number.isFinite(amount) || amount <= 0) throw new Error("Enter a positive funding amount."); if (!campaignId) throw new Error("Live mode requires the existing campaign ID to fund."); const res = await fundCampaign({ campaignId, amount: fundAmount }); setMessage(`Live Testnet campaign funding submitted: ${res?.hash || "pending hash"}. Await wallet/RPC confirmation; local accounting is not live state.`); });
  const createLiveCampaign = () => run("Creating campaign", async () => { if (!campaignId || !token) throw new Error("Live mode requires campaign ID and token contract address from the operator."); const res = await createCampaign({ campaignId, token }); setMessage(`Live Testnet campaign creation submitted: ${res?.hash || "pending hash"}.`); });
  const approve = () => run("Approving merchant", async () => { if (mode === "demo") { setMerchant(DEMO_MERCHANT); setMessage("Local demo merchant approved using a demo address. Never on-chain."); return; } if (!merchant || !merchantProfileHash) throw new Error("Live mode requires merchant address and merchant profile hash."); const res = await approveMerchant({ merchant, profileHash: merchantProfileHash }); setMessage(`Live Testnet merchant approval submitted: ${res?.hash || "pending hash"}`); });
  const createAidCase = () => run("Creating beneficiary case", async () => { if (mode === "demo") { setMessage("Local demo case created with opaque IDs only. No personal data and never on-chain."); return; } if (!campaignId || !caseId || !caseRecordHash) throw new Error("Live mode requires campaign ID, case ID, and case record hash."); const res = await createCase({ campaignId, caseId, caseRecordHash }); setMessage(`Live Testnet case creation submitted: ${res?.hash || "pending hash"}`); });
  const issue = () => run("Issuing voucher", async () => { const amount = Number(voucherAmount); if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "issue", amount, category }); setMessage(`Local demo voucher reserved ${amount.toFixed(2)} units for ${category}. Never on-chain.`); return; } if (!Number.isFinite(amount) || amount <= 0) throw new Error("Enter a positive voucher amount."); if (!voucherId || !campaignId || !caseId || !merchant || !purposeHash) throw new Error("Live mode requires voucher ID, campaign ID, case ID, merchant address, and purpose hash."); const res = await issueVoucher({ voucherId, campaignId, caseId, merchant, amount: voucherAmount, category, purposeHash, expiresAt: Math.floor(Date.now() / 1000) + 604800 }); setMessage(`Live Testnet voucher issuance submitted: ${res?.hash || "pending hash"}.`); });
  const redeem = () => run("Redeeming voucher", async () => { if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "redeem" }); setMessage("Local demo merchant redemption recorded with evidence[0] digest and opaque record ID. Never on-chain."); return; } if (!voucherId || !contentDigest || !evidenceRecordId) throw new Error("Live mode requires voucher ID, initial evidence digest, and opaque evidence record ID."); const res = await redeemVoucher({ voucherId, contentDigest, evidenceRecordId }); setMessage(`Live Testnet redemption submitted: ${res?.hash || "pending hash"}.`); });
  const freeze = () => run("Freezing claim", async () => { if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "freeze" }); setMessage("Local demo admin freeze recorded with reason digest only. Never on-chain."); return; } if (!voucherId || !reasonHash) throw new Error("Live mode requires voucher ID and admin freeze reason digest."); const res = await freezeClaim({ voucherId, reasonHash }); setMessage(`Live Testnet freeze submitted: ${res?.hash || "pending hash"}.`); });
  const appendRevision = () => run("Appending evidence revision", async () => { if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "appendRevision" }); setMessage("Local demo merchant evidence[1] appended after freeze. Never on-chain."); return; } if (!voucherId || !revisionDigest || !revisionRecordId) throw new Error("Live mode requires voucher ID, revision digest, and opaque revision record ID."); const res = await appendEvidenceRevision({ voucherId, contentDigest: revisionDigest, evidenceRecordId: revisionRecordId }); setMessage(`Live Testnet evidence revision submitted: ${res?.hash || "pending hash"}.`); });
  const decide = (decision: ClaimDecision) => run(decision === ClaimDecision.Approve ? "Approving claim" : "Rejecting claim", async () => { if (mode === "demo") { setWalkthrough(null); applyLocalDemoAction({ type: "decide", decision: decision === ClaimDecision.Approve ? "Approve" : "Reject" }); setMessage(decision === ClaimDecision.Approve ? "Clean local demo paid: verifier approved atomic payout. Never on-chain." : "Disputed local demo rejected: reservation released to available, no payout. Never on-chain."); return; } if (!voucherId || !decisionReasonHash) throw new Error("Live mode requires voucher ID and verifier decision reason digest."); const res = await decideClaim({ voucherId, decision, reasonHash: decisionReasonHash }); setMessage(`Live Testnet verifier ${decision.toLowerCase()} submitted: ${res?.hash || "pending hash"}.`); });
  const startWalkthrough = (name: "clean" | "disputed") => run(`Starting ${name} walkthrough`, async () => { setDemoState(bootstrapIssuedDemo(25)); setWalkthrough({ name, step: 0 }); setMessage(`${name === "clean" ? "Clean" : "Disputed"} walkthrough started at Issued with 25 reserved. Use Advance walkthrough to execute each validated transition.`); });
  const advanceWalkthrough = () => run("Advancing walkthrough", async () => { if (!walkthrough) throw new Error("Start a clean or disputed walkthrough first."); const steps = walkthrough.name === "clean" ? [{ type: "redeem" as const }, { type: "decide" as const, decision: "Approve" as const }] : [{ type: "redeem" as const }, { type: "freeze" as const }, { type: "appendRevision" as const }, { type: "decide" as const, decision: "Reject" as const }]; const action = steps[walkthrough.step]; if (!action) throw new Error("Walkthrough is already complete. Reset or start another walkthrough."); const nextState = applyDemoAction(demoState(), action); setDemoState(nextState); const nextStep = walkthrough.step + 1; setWalkthrough(nextStep >= steps.length ? null : { ...walkthrough, step: nextStep }); setMessage(nextStep >= steps.length ? `${walkthrough.name === "clean" ? "Clean" : "Disputed"} walkthrough complete.` : `Advanced step ${nextStep}; next: ${walkthrough.name === "clean" ? "Paid (verifier approval)" : ["Frozen (admin)", "evidence[1]", "Rejected (verifier)"][nextStep - 1]}.`); });
  const walkthroughCurrent = walkthrough ? (walkthrough.step === 0 ? "Issued" : walkthrough.name === "clean" ? "Redeemed/evidence[0]" : ["Redeemed/evidence[0]", "Frozen (admin)", "evidence[1]"][walkthrough.step - 1]) : "None";
  const walkthroughNext = walkthrough ? (walkthrough.name === "clean" ? ["Redeemed/evidence[0]", "Paid (verifier approval)"][walkthrough.step] : ["Redeemed/evidence[0]", "Frozen (admin)", "evidence[1]", "Rejected (verifier)"][walkthrough.step]) : "Start a walkthrough";

  return <section className="space-y-4 pb-24" data-testid="aid-workspace">
    <div className="p-4 rounded-2xl border border-teal-500/20 bg-space-900/70"><h2 className="text-xl font-bold text-white">Aethyr Aid lifecycle</h2><p className="text-sm text-slate-300">Mobile-first role workspaces for admin bootstrap, merchant redemption, admin emergency freeze, and verifier review. Live Testnet requires role-disjoint wallets: admin cannot act as verifier, and merchant submits merchant-only evidence actions.</p></div>
    <div className="grid grid-cols-2 gap-2"><button onClick={() => setMode("demo")} className={`rounded-xl p-3 ${mode === "demo" ? "bg-teal-500 text-space-950" : "bg-space-800 text-slate-300"}`}>Local demo</button><button onClick={() => setMode("live")} className={`rounded-xl p-3 ${mode === "live" ? "bg-teal-500 text-space-950" : "bg-space-800 text-slate-300"}`}>Live Testnet</button></div>
    {isLoading && <div className="text-slate-300">Loading wallet state…</div>}{pending && <div className="text-slate-300">Pending submission: {pending}…</div>}{mode === "live" && !isConnected && <div className="rounded-xl border border-amber-500/30 p-3 text-amber-200">Disconnected: connect the correct Testnet role wallet before submitting.</div>}
    <div className="rounded-2xl bg-space-900 p-4 border border-space-700"><p className="text-xs uppercase text-slate-400">Demo-only accounting</p><div className="mt-2 grid grid-cols-4 gap-2 text-center"><div><b className="text-white">{total.toFixed(2)}</b><p className="text-xs text-slate-400">Total demo</p></div><div><b className="text-emerald-300">{available.toFixed(2)}</b><p className="text-xs text-slate-400">Available</p></div><div><b className="text-amber-300">{reserved.toFixed(2)}</b><p className="text-xs text-slate-400">Reserved</p></div><div><b className="text-sky-300">{paid.toFixed(2)}</b><p className="text-xs text-slate-400">Paid</p></div></div><p className="mt-2 text-xs text-slate-400">Status: {status}. {total === 0 ? "Empty state: no demo funds yet." : "History/accounting are local demo state only."}</p></div>
    <div className="space-y-2 rounded-2xl border border-space-700 p-3"><p className="text-xs uppercase text-slate-400">Guided walkthrough</p><p className="text-sm text-slate-300">Current: {walkthroughCurrent}. Next: {walkthroughNext}. History below records every validated transition.</p><div className="grid grid-cols-1 gap-2 sm:grid-cols-4"><button onClick={() => startWalkthrough("clean")} disabled={!!pending} className="rounded-xl bg-emerald-500 p-3 font-bold text-space-950 disabled:opacity-50">Start clean walkthrough</button><button onClick={() => startWalkthrough("disputed")} disabled={!!pending} className="rounded-xl bg-amber-500 p-3 font-bold text-space-950 disabled:opacity-50">Start disputed walkthrough</button><button onClick={advanceWalkthrough} disabled={!!pending || !walkthrough} className="rounded-xl bg-sky-500 p-3 font-bold text-space-950 disabled:opacity-50">Advance walkthrough</button><button onClick={resetDemo} disabled={!!pending} className="rounded-xl bg-space-800 p-3 text-white disabled:opacity-50">Reset demo</button></div></div>
    <p className="text-xs text-slate-400">Privacy: enter only 32-byte digests/IDs. No raw evidence or beneficiary personal data.</p>
    {mode === "live" && <div className="space-y-2"><input aria-label="Campaign ID" placeholder="32-byte campaign ID hex" value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Token address" placeholder="Token contract address" value={token} onChange={(e) => setToken(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><button disabled={!!pending || liveDisabled} onClick={createLiveCampaign} className="w-full rounded-xl bg-space-800 p-3 text-white disabled:opacity-50">Create live campaign</button></div>}
    <section className="space-y-2 rounded-2xl border border-cyan-500/20 p-3"><h3 className="font-semibold text-white">Admin bootstrap workspace</h3><input aria-label="Funding amount" value={fundAmount} onChange={(e) => setFundAmount(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><button disabled={!!pending || liveDisabled} onClick={fund} className="w-full rounded-xl bg-teal-500 p-3 font-bold text-space-950 disabled:opacity-50">Fund campaign</button>{mode === "live" && <><input aria-label="Merchant address" placeholder="Merchant address" value={merchant} onChange={(e) => setMerchant(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Merchant profile hash" placeholder="32-byte merchant profile hash hex" value={merchantProfileHash} onChange={(e) => setMerchantProfileHash(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Case ID" placeholder="32-byte case ID hex" value={caseId} onChange={(e) => setCaseId(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Case record hash" placeholder="32-byte case record hash hex" value={caseRecordHash} onChange={(e) => setCaseRecordHash(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Voucher ID" placeholder="32-byte voucher ID hex" value={voucherId} onChange={(e) => setVoucherId(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Purpose hash" placeholder="32-byte voucher purpose hash hex" value={purposeHash} onChange={(e) => setPurposeHash(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/></>}<button disabled={!!pending || liveDisabled} onClick={approve} className="w-full rounded-xl bg-space-800 p-3 text-white disabled:opacity-50">Approve merchant</button><button disabled={!!pending || liveDisabled} onClick={createAidCase} className="w-full rounded-xl bg-space-800 p-3 text-white disabled:opacity-50">Create beneficiary case</button><input aria-label="Voucher amount" value={voucherAmount} onChange={(e) => setVoucherAmount(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><select aria-label="Voucher category" value={category} onChange={(e) => setCategory(e.target.value as VoucherCategory)} className="w-full rounded-xl bg-space-800 p-3 text-white"><option>Food</option><option>Medicine</option><option>Shelter</option><option>Other</option></select><button disabled={!!pending || liveDisabled} onClick={issue} className="w-full rounded-xl bg-teal-500 p-3 font-bold text-space-950 disabled:opacity-50">Issue voucher</button></section>
    <section className="space-y-2 rounded-2xl border border-emerald-500/20 p-3"><h3 className="font-semibold text-white">Merchant redemption workspace</h3><input aria-label="Initial evidence digest" placeholder="32-byte evidence[0] content digest" value={contentDigest} onChange={(e) => setContentDigest(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Evidence record ID" placeholder="32-byte opaque evidence record ID" value={evidenceRecordId} onChange={(e) => setEvidenceRecordId(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><button disabled={!!pending || liveDisabled} onClick={redeem} className="w-full rounded-xl bg-emerald-500 p-3 font-bold text-space-950 disabled:opacity-50">Redeem voucher with evidence[0]</button><input aria-label="Evidence revision digest" placeholder="32-byte evidence[1] digest after freeze" value={revisionDigest} onChange={(e) => setRevisionDigest(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><input aria-label="Evidence revision record ID" placeholder="32-byte opaque revision record ID" value={revisionRecordId} onChange={(e) => setRevisionRecordId(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><button disabled={!!pending || liveDisabled || (mode === "demo" && (status !== "frozen" || hasRevision))} onClick={appendRevision} className="w-full rounded-xl bg-space-800 p-3 text-white disabled:opacity-50">Append exactly one evidence[1] after freeze</button></section>
    <section className="space-y-2 rounded-2xl border border-amber-500/20 p-3"><h3 className="font-semibold text-white">Admin emergency-freeze control</h3><input aria-label="Freeze reason digest" placeholder="32-byte reason digest only" value={reasonHash} onChange={(e) => setReasonHash(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><button disabled={!!pending || liveDisabled} onClick={freeze} className="w-full rounded-xl bg-amber-500 p-3 font-bold text-space-950 disabled:opacity-50">Admin freeze claim</button></section>
    <section className="space-y-2 rounded-2xl border border-purple-500/20 p-3"><h3 className="font-semibold text-white">Verifier-only review panel</h3><p className="text-xs text-slate-400">Verifier decisions expose only Approve or Reject. Freeze is an admin control, not a verifier decision.</p><input aria-label="Verifier decision reason digest" placeholder="32-byte verifier reason digest" value={decisionReasonHash} onChange={(e) => setDecisionReasonHash(e.target.value)} className="w-full rounded-xl bg-space-800 p-3 text-white"/><div className="grid grid-cols-2 gap-2"><button disabled={!!pending || liveDisabled} onClick={() => decide(ClaimDecision.Approve)} className="rounded-xl bg-emerald-500 p-3 font-bold text-space-950 disabled:opacity-50">Verifier approve / atomic payout</button><button disabled={!!pending || liveDisabled} onClick={() => decide(ClaimDecision.Reject)} className="rounded-xl bg-red-500 p-3 font-bold text-white disabled:opacity-50">Verifier reject / release reservation</button></div></section>
    {message && <div className="rounded-xl border border-emerald-500/30 p-3 text-emerald-200">{message}</div>}{error && <div className="rounded-xl border border-red-500/30 p-3 text-red-200">Recoverable error: {error}</div>}<div className="rounded-xl bg-space-900 p-3"><p className="text-xs uppercase text-slate-400">Visible state/history</p>{history.length === 0 ? <p className="text-sm text-slate-400">No local demo activity yet.</p> : <ul className="list-disc pl-5 text-sm text-slate-300">{history.map((h) => <li key={h}>{h}</li>)}</ul>}</div>
    <p className="text-[11px] text-slate-500">Mode: {mode === "demo" ? "deterministic local demo — never on-chain" : `Live Testnet using ${address || "no wallet"}`}. IDs shown for demo: {DEMO_CAMPAIGN_ID.slice(0, 4)}/{DEMO_CASE_ID.slice(0, 4)}/{DEMO_VOUCHER_ID.slice(0, 4)}.</p>
  </section>;
}
